# Release Configuration for Jupyter MCP Server
# This file tracks release metadata and deployment settings

release:
  version: "1.0.0"
  release_date: "2025-01-22"
  stability: "stable"
  compatibility: "production-ready"
  
# Version scheme: MAJOR.MINOR.PATCH
# MAJOR: Breaking changes or major new features
# MINOR: New features, backward compatible
# PATCH: Bug fixes, no new features

versioning:
  scheme: "semantic"
  current_major: 1
  current_minor: 0
  current_patch: 0
  
# Environment compatibility
environments:
  python_versions: ["3.10", "3.11", "3.12"]
  jupyter_versions: [">=4.1.8"]
  mcp_versions: [">=1.10.1"]
  
# Dependencies locked for this release
dependencies:
  core:
    - "jupyter-kernel-client>=0.7.3"
    - "jupyter-nbmodel-client>=0.13.5" 
    - "mcp[cli]>=1.10.1"
    - "pydantic"
    - "uvicorn"
    - "click"
    - "fastapi"
  
  docker:
    - "jupyterlab==4.4.1"
    - "jupyter-collaboration==4.0.2"
    - "datalayer_pycrdt==0.12.17"

# Release artifacts
artifacts:
  - name: "python-package"
    type: "wheel"
    location: "dist/"
  - name: "docker-image"
    type: "container"
    location: "docker-compose.yml"
  - name: "test-suite"
    type: "validation"
    location: "mcp_test_suite.py"

# Release validation checklist
validation:
  required_tests:
    - "mcp_test_suite.py"
    - "interactive_mcp_test.html"
  success_criteria:
    - "100% test pass rate"
    - "All 30 test cases passing"
    - "No Docker errors"
    - "Real-time collaboration working"
  
# Issue tracking
issues:
  repository: "your-company/jupyter-mcp-server"
  labels:
    - "version:1.0.0"
    - "production"
  milestone: "v1.0.0-stable" 