services:
  jupyterlab:
    build:
      context: .
      dockerfile: jupyterlab.Dockerfile
    container_name: jupyter-mcp-jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=MY_TOKEN
    working_dir: /home/jovyan/
    command: >
      jupyter lab --port=8888 --ip=0.0.0.0 --allow-root --no-browser
      --ServerApp.token='MY_TOKEN'
      --ServerApp.disable_check_xsrf=True
      --ServerApp.allow_origin='*'
      --ServerApp.allow_remote_access=True
      --ServerApp.root_dir='/home/jovyan/'
      --LabApp.collaborative=True
      --ServerApp.tornado_settings='{"headers":{"Content-Security-Policy":"frame-ancestors '\''self'\'' *;"}}'
    networks:
      - jupyter-mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/kernelspecs?token=MY_TOKEN"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  jupyter-mcp-server:
    build: .
    container_name: jupyter-mcp-server
    ports:
      - "4040:4040"
    environment:
      - TRANSPORT=streamable-http
      - RUNTIME_URL=http://jupyterlab:8888
      - ROOM_URL=http://jupyterlab:8888
      - RUNTIME_TOKEN=MY_TOKEN
      - ROOM_TOKEN=MY_TOKEN
    depends_on:
      jupyterlab:
        condition: service_healthy
    networks:
      - jupyter-mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040/api/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  jupyter-mcp-network:
    driver: bridge 